name: Build and Push to ECR
on:
  push:
    branches:
      - master  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and tag Docker image
        run: |
          docker build -t asantegyabengsamuel_weatherapp .
          docker asantegyabengsamuel_weatherapp:latest public.ecr.aws/h2l8y6e3/asantegyabengsamuel_weatherapp:latest
      - name: Push image to Amazon ECR Public
        run: |
          docker push public.ecr.aws/h2l8y6e3/asantegyabengsamuel_weatherapp
